import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
//Components
import SelectLang from "@/components/SelectLang";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <main className="min-h-screen bg-gradient-to-r from-[#6eda78] to-[#ffa200]">
          <SelectLang />
          {children}
        </main>
      </body>
    </html>
  );
}
